# Server
server:
  # 端口
  port: 80
# Spring
spring:
  application:
    # 应用名称
    name: chatgpt-robot
# 应用配置
app:
  # 微信公众号
  wx-mp:
    appId: 微信appid
    secret: 微信secret
    token: 微信token
    aesKey: 微信aesKey
  # chatgpt
  chatgpt:
    sk: chatgpt的sk
    url: https://api.openai.com/v1/chat/completions
