# Server
server:
  # 端口
  port: 80
# Spring
spring:
  application:
    # 应用名称
    name: chatgptRobot
# 应用配置
app:
  # weixin
  wx:
    appId: wx6b6d35a95ac56ff5
    secret: a81f8f70e8180c8e375ef8d9fb62e339
    token: leo12345678
    aesKey: zL9491Fh730oAdryvPAyJ1lVKVyoGOzMaF9vzRAL5V8
  # chatgpt
  chatgpt:
    sk: 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
    url: https://api.openai.com/v1/chat/completions
